/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_careerop_ndktest_NativeClass */

#ifndef _Included_org_careerop_ndktest_NativeClass
#define _Included_org_careerop_ndktest_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_careerop_ndktest_NativeClass
 * Method:    getMessageFormJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_careerop_ndktest_NativeClass_getMessageFormJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
